### ISSUE TITLE
Freshness of email domain list

### ISSUE THREAD

**Issue by curiousercreative** [sl-julienamblard/email-misspelled#38]
The top100 list for example hasn't been updated since July 2020. Was the underlying data fresh at that point? Is there a source you used previously that I can pull from to create a PR to update?

**Comment by sl-julienamblard** [comment]
Hello @curiousercreative 
Sorry for the delay I'm pretty busy theses days.

When I've write this package I was sourcing around multiple analyses. For now I haven't found any most recent list.
I'm not sure it changed a lot in one year. But if you found a most recent/complete/accurate list of the top 100 used email domain feel free to make a PR !

**Comment by curiousercreative** [comment]
Closing for now, but I'll submit as PR if/when I come across a fresher dataset
